# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=6)),
                ('breed', models.CharField(choices=[('BS', 'Bos taurus'), ('AU', 'Aubrac')], default='BS', max_length=15)),
                ('discription', models.CharField(max_length=1000)),
                ('lactating', models.BooleanField(default='False')),
                ('feeding_skeem', models.CharField(max_length=100)),
                ('condition_score', models.PositiveSmallIntegerField(default=0)),
                ('injection_type', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('injection_LastDate', models.CharField(max_length=100)),
                ('insemination', models.CharField(max_length=100)),
            ],
        ),
    ]
