# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='cow_img',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
