# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_cow_cow_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify_img', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
