# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_cattleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.DateTimeField()),
                ('birth_date', models.DateField()),
                ('description', models.CharField(max_length=100000)),
                ('lactating', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=6)),
                ('feeding_scheme', models.CharField(max_length=100)),
                ('condition_score', models.CharField(choices=[(' 1-10 pts ', ' 1-10 pts'), ('10-20 pts', '10-20 pts'), ('20-30 pts', '20-30 pts'), ('30-40 pts', '30-40 pts'), ('50-60 pts', '50-60 pts'), ('60-70 pts', '60-70 pts'), ('70-80 pts', '70-80 pts'), ('70-80 pts', '70-80 pts'), ('80-90 pts', '80-90 pts'), ('90-100 pts', '90-100 pts')], default=' 1-10 pts ', max_length=6)),
                ('injection_type', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('injection_Last_Date', models.DateTimeField()),
                ('insemination_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cow',
            name='condition_score',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='feeding_skeem',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='injection_LastDate',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='injection_type',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='insemination',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='lactating',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='weight',
        ),
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(choices=[('Bos taurus', 'Bos taurus'), ('Aubrac', 'Aubrac')], default='Bos taurus', max_length=15),
        ),
        migrations.AlterField(
            model_name='cow',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=6),
        ),
        migrations.AddField(
            model_name='cattlelog',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Cow'),
        ),
    ]
