# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_auto_20170825_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlelog',
            name='condition_score',
            field=models.CharField(choices=[(' 1-10 pts ', ' 1-10 pts'), ('10-20 pts', '10-20 pts'), ('20-30 pts', '20-30 pts'), ('30-40 pts', '30-40 pts'), ('50-60 pts', '50-60 pts'), ('60-70 pts', '60-70 pts'), ('70-80 pts', '70-80 pts'), ('70-80 pts', '70-80 pts'), ('80-90 pts', '80-90 pts'), ('90-100 pts', '90-100 pts')], default=' 1-10 pts ', max_length=15),
        ),
        migrations.AlterField(
            model_name='cattlelog',
            name='lactating',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=15),
        ),
    ]
