# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20170825_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlelog',
            name='birth_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
