# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_auto_20170825_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle_Retrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_video_1', models.FileField(default=None, upload_to='')),
                ('cow_video_2', models.FileField(default=None, upload_to='')),
                ('cow_video_3', models.FileField(default=None, upload_to='')),
                ('cow_video_4', models.FileField(default=None, upload_to='')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Cow')),
            ],
        ),
    ]
